name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        cd pytube
        pip install -e .
        cd ..

    - name: Run tests
      run: python -m unittest discover -s ./tests
